### ISSUE TITLE
Influxdb: error when no data returned

### ISSUE THREAD

**Issue by rozetko** [CorpGlory/grafana-datasource-kit#23]
Currently you get error when no data for given range is returned in `InfluxdbMetric`

![image](https://user-images.githubusercontent.com/1989898/45951189-37e92680-c00b-11e8-9d44-fa1a058b5859.png)

Guess it would be better to do like in `GraphiteMetric`: 
```javascript
if(res.data !== undefined && res.data.length < 1) {
  console.log('datasource return empty response, no data');
  return {
    columns: ['timestamp', 'target'],
    values: []
  };
}
```

@amper43 @jonyrock what do you think? Should we handle it? Maybe it should be handled by lib user?

**Comment by jonyrock** [comment]
@rozetko  I don`t like how it is made in prometheus. 
```
if(res.data === undefined) {
  throw new Error('undefined error');
}
```
and then continue


Please think for a second, what you gonna do if `res.data` IS `undefined`?
