### ISSUE TITLE
Empty dataframe returned when using InfluxDB aggregation

### ISSUE THREAD

**Issue by VargBurz** [CorpGlory/grafana-datasource-kit#31]
If `mean()` aggregation is chosen, only None values are returned.
Maybe it has something to do with `$interval`

![image](https://user-images.githubusercontent.com/39257464/48513943-3d762680-e86e-11e8-8b20-1e318bf70185.png)

How to reproduce:
* Choose `mean()` aggregation with `time($interval)` grouping

![image](https://user-images.githubusercontent.com/39257464/48513979-55e64100-e86e-11e8-8cda-758c0bdddf38.png)

**Comment by rozetko** [comment]
Was a problem in hastic-server
Fixed in https://github.com/hastic/hastic-server/pull/248
