### ISSUE TITLE
Cannot set property 'gte' of undefined

### ISSUE THREAD

**Issue by amper43** [CorpGlory/grafana-datasource-kit#80]
![image](https://user-images.githubusercontent.com/5675912/61292500-03349e80-a7da-11e9-8513-3f59d241abf1.png)

This error occurs for Elasticsearch because of we use hardcoded date field name instead of name from datasource structure:
https://github.com/CorpGlory/grafana-datasource-kit/blob/master/src/metrics/elasticsearch_metric.ts#L25

**Comment by moarpheus** [comment]
I see, thank you!
